In [1]:
import torch

In [2]:
torch.__version__

'1.0.1'

In [5]:
cu = torch.cuda.cudaStatus()

In [6]:
cu.ERROR_NOT_READY

34

In [7]:
cu.SUCCESS

0

## 1. 텐서 내의 new 메소드 사용하기 

In [8]:
tensor = torch.ones((2,), dtype=torch.float64)

In [9]:
tensor.new_full((3, 4), 3.141592)

tensor([[3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416]], dtype=torch.float64)

In [12]:
data = torch.rand(3,4)

#### 권고사항이 아니므로 다른 방법을 사용할 것 

In [13]:
tensor.new_tensor(data)

C:\Users\dahlmoon\Anaconda3\envs\pytorch_gpu\lib\site-packages\ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


tensor([[0.6155, 0.6595, 0.6915, 0.9111],
        [0.1156, 0.6810, 0.7457, 0.8335],
        [0.2626, 0.5287, 0.7952, 0.8782]], dtype=torch.float64)

In [15]:
tensor.clone()

tensor([1., 1.], dtype=torch.float64)

### new_empty 메소드 사용하기 

In [16]:
tensor = torch.ones(())

In [17]:
tensor.new_empty((2, 3))

tensor([[-1.7436e+26,  4.5914e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

### new_ones , new_zeros 메소드 사용하기 

In [18]:
tensor = torch.tensor((), dtype=torch.int32)

In [19]:
tensor.new_ones((2, 3))

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [20]:
tensor.new_zeros((2, 3))

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)