In [1]:
import torch

### 1.  tensor 배열을 만들기

### 스칼라 - 텐서 0차

In [6]:
x = torch.tensor(10)

In [15]:
x

tensor(10)

#### 원소가 하나일 때 그 값을 읽을 때 사용 

In [65]:
x.item()

10

#### 텐서 차원 알아보기

In [14]:
x.dim()

0

#### 텐서 타입 알아보기 

In [7]:
type(x)

torch.Tensor

#### 내부 구성 자료형 알아보기 

In [8]:
x.dtype

torch.int64

#### 스칼라는 배열이 아니므로 인덱스 검색이 불가 

In [10]:
try :
    x[0]
except Exception as e :
    print(e)

invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number


#### 배열의 모양 즉 스칼라는 배열이 아니라서 모양이 존재하지 않는다

In [11]:
x.shape

torch.Size([])

In [12]:
x.size()

torch.Size([])

###  벡터 - 텐서 1차

In [16]:
v = torch.tensor([0.1, 1.2])

In [17]:
v

tensor([0.1000, 1.2000])

In [18]:
v.dim()

1

In [19]:
v.shape

torch.Size([2])

In [20]:
v.size()

torch.Size([2])

### 행렬 - 텐서 2차

In [61]:
a = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])

In [62]:
a.data

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [63]:
a.dim()

2

#### 배열의 모양과 자료형 알아보기

In [52]:
a.shape

torch.Size([3, 2])

In [53]:
a.dtype

torch.float32

#### 내부 원소의 확장을 알 수 있음 

In [54]:
a.stride()

(2, 1)

## 2.  파이토치 배열도 새로운 슬라이스 처리할 때는 뷰만 처리함

### 슬라이스로 다른 변수 할당

In [24]:
b = a[:]

In [25]:
b[0,0] = 999

In [26]:
b

tensor([[999.0000,   1.2000],
        [  2.2000,   3.1000],
        [  4.9000,   5.2000]])

In [27]:
a

tensor([[999.0000,   1.2000],
        [  2.2000,   3.1000],
        [  4.9000,   5.2000]])

### view 메소드로 공유하기 

In [68]:
d = b.view(3,2)

In [69]:
d

tensor([[999.0000,   1.2000],
        [  2.2000,   3.1000],
        [  4.9000,   5.2000]])

### 동일한 데이터 메모리를 사용하는 지 확인

In [72]:
b.data.

tensor([[999.0000,   1.2000],
        [  2.2000,   3.1000],
        [  4.9000,   5.2000]])

In [73]:
d.data

tensor([[999.0000,   1.2000],
        [  2.2000,   3.1000],
        [  4.9000,   5.2000]])

In [70]:
import numpy as np

In [71]:
np.may_share_memory(d,b)

True

### 새로운 텐서를 만들어서 처리하려면 clone 을 사용 

In [29]:
c = a.clone()

In [74]:
np.may_share_memory(a,c)

False

In [30]:
c[0][0] = 888

In [31]:
c

tensor([[888.0000,   1.2000],
        [  2.2000,   3.1000],
        [  4.9000,   5.2000]])

In [32]:
a

tensor([[999.0000,   1.2000],
        [  2.2000,   3.1000],
        [  4.9000,   5.2000]])

### 배열의 크기 알아보기

In [33]:
a.shape

torch.Size([3, 2])

In [34]:
a.size()

torch.Size([3, 2])

### 연산자 알아보기

In [36]:
d = a+b

In [37]:
d

tensor([[1998.0000,    2.4000],
        [   4.4000,    6.2000],
        [   9.8000,   10.4000]])

In [38]:
a

tensor([[999.0000,   1.2000],
        [  2.2000,   3.1000],
        [  4.9000,   5.2000]])

In [39]:
b

tensor([[999.0000,   1.2000],
        [  2.2000,   3.1000],
        [  4.9000,   5.2000]])

### 메소드로 연산하기

In [40]:
e = a.add(b)

In [41]:
e

tensor([[1998.0000,    2.4000],
        [   4.4000,    6.2000],
        [   9.8000,   10.4000]])

In [42]:
a

tensor([[999.0000,   1.2000],
        [  2.2000,   3.1000],
        [  4.9000,   5.2000]])

In [43]:
b

tensor([[999.0000,   1.2000],
        [  2.2000,   3.1000],
        [  4.9000,   5.2000]])

### 내부 값 수정 배열 연산은 뒤에  언더바가 붙어있다. 

In [44]:
c.add_(b)

tensor([[1887.0000,    2.4000],
        [   4.4000,    6.2000],
        [   9.8000,   10.4000]])

In [45]:
c

tensor([[1887.0000,    2.4000],
        [   4.4000,    6.2000],
        [   9.8000,   10.4000]])

In [46]:
b

tensor([[999.0000,   1.2000],
        [  2.2000,   3.1000],
        [  4.9000,   5.2000]])