In [1]:
import torch

## 1. 파이토치 텐서에 자료형을 지정하기

In [2]:
torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

## 2. gpu 디바이스 지정하기 

In [3]:
cuda0 = torch.device('cuda:0')

In [4]:
cuda0

device(type='cuda', index=0)

In [5]:
torch.ones([2, 4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

## 3. 텐서 생성해서 내부 배열원소 검색하기 

In [6]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1][2])

tensor(6)


In [7]:
torch.tensor(9)

tensor(9)

In [8]:
x[0][1] = 8
print(x)

tensor([[1, 8, 3],
        [4, 5, 6]])


## 4. 파이토치 텐서 내부 속성과 메소드 처리

In [9]:
x = torch.tensor([[1]])

In [10]:
x

tensor([[1]])

In [11]:
x.item()

1

In [12]:
x.size()

torch.Size([1, 1])

In [13]:
x.stride()

(1, 1)

In [15]:
x.dtype

torch.int64