In [1]:
import torch

In [2]:
torch.__version__

'1.1.0'

In [3]:
import numpy as np

### 5 행 3열을 초기화 되지 않도록 생성하기

#### pytorch로 생성

In [5]:
x = torch.empty(5, 3)

In [6]:
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.1614e-41],
        [0.0000e+00, 2.2369e+08, 0.0000e+00],
        [0.0000e+00, 2.8699e-42, 2.8699e-42],
        [       nan,        nan, 2.5794e+13]])

In [11]:
x.shape

torch.Size([5, 3])

In [13]:
x.dim()

2

#### 넘파이 모듈은 내부에 튜플로 배열을 생성

In [9]:
y= np.empty((5,3))

In [10]:
y

array([[5.92878775e-323, 0.00000000e+000, 2.23570379e-314],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.26480805e-321, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [12]:
y.shape

(5, 3)

In [14]:
y.ndim

2

### 무작위 배열 만들기

#### pytorch

In [15]:
torch.rand(5, 3)

tensor([[0.1365, 0.5567, 0.6068],
        [0.1243, 0.4320, 0.5207],
        [0.4322, 0.2033, 0.8959],
        [0.1922, 0.6052, 0.0834],
        [0.5707, 0.3893, 0.2728]])

#### numpy

In [16]:
np.random.rand(5,3)

array([[0.26147194, 0.79278438, 0.07134403],
       [0.36416969, 0.35545343, 0.99228792],
       [0.43479538, 0.33779261, 0.37509785],
       [0.945574  , 0.10354191, 0.52452544],
       [0.48274874, 0.42600069, 0.46264305]])

### 자료형을 넣고 처리하기

#### pytorch

In [18]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [23]:
#### numpy

In [20]:
np.int64

numpy.int64

In [22]:
np.zeros((5,3), dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### 일반 배열을 함수로 생성하기

####  1차원 텐서 : pytorch

In [24]:
torch.tensor([5.5, 3])

tensor([5.5000, 3.0000])

#### 1 차원 배열 : numpy

In [25]:
np.array([5.5, 3])

array([5.5, 3. ])

#### 텐서를 넘파이로 변환 후에 비교하기 

In [27]:
torch.tensor([5.5, 3]).numpy() == np.array([5.5, 3])

array([ True,  True])

### 기존 텐서를 가지고 다른 텐서 만들기 

In [28]:
x = x.new_ones(5, 3, dtype=torch.double)  

In [30]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

#### 자료형을 축소

In [29]:
y = torch.randn_like(x, dtype=torch.float)  

In [31]:
y

tensor([[ 0.5616,  0.5644, -0.2471],
        [ 0.3032,  1.6338,  0.3195],
        [-0.3494,  1.4862, -0.7852],
        [-0.1874, -1.8978,  1.0484],
        [-0.2578, -0.3007,  0.5724]])

In [32]:
y.dtype

torch.float32

### 파이토치를 넘파이로 변환해도 실제 내부의 데이터를 공유

In [33]:
a = torch.ones(5)

In [34]:
a

tensor([1., 1., 1., 1., 1.])

In [38]:
b = a.numpy()

In [39]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
#### 두 객체의 데이터는 

In [40]:
np.may_share_memory(a,b)

True

#### 내부 원소 값 갱신하는 연산자를 가지고 변경하면 넘파이로 변환된 정보도 갱신

In [41]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [42]:
b

array([2., 2., 2., 2., 2.], dtype=float32)