## 파이토치 참조

    https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/

In [1]:
import torch

In [2]:
torch.__version__

'1.1.0'

## 동일한 랜덤 처리 유지하기

###  균일분포(uniform), 정규분포(normal)

In [3]:
torch.manual_seed(1)


v1 = torch.rand(2, 3)            # Initialize with random number (uniform distribution)
v2 = torch.randn(2, 3)           # With normal distribution (SD=1, mean=0)


In [5]:
v1

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])

In [6]:
v2

tensor([[ 0.5636,  1.1431,  0.8590],
        [ 0.7056, -0.3406, -1.2720]])

### Size 4. Random permutation of integers from 0 to 3


In [ ]:
v3 = torch.randperm(4)

In [7]:
v3

tensor([2, 0, 1, 3])

In [4]:
torch.manual_seed(1)


v11 = torch.rand(2, 3)            # Initialize with random number (uniform distribution)
v22 = torch.randn(2, 3)           # With normal distribution (SD=1, mean=0)
v33 = torch.randperm(4)

In [8]:
v11

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])

In [9]:
v22

tensor([[ 0.5636,  1.1431,  0.8590],
        [ 0.7056, -0.3406, -1.2720]])

In [10]:
v33

tensor([2, 0, 1, 3])

### 타입 변경

In [11]:
x = torch.randn(5, 3).type(torch.FloatTensor)

In [12]:
x

tensor([[-0.6919, -0.4043,  0.2222],
        [ 0.5773, -1.7637,  0.2264],
        [-0.2355,  0.3019, -0.2770],
        [ 0.4771, -0.1103,  0.2913],
        [ 0.5848,  0.2149, -0.4090]])

In [13]:
x.dtype

torch.float32

In [14]:
y = torch.randn(5, 3).type(torch.IntTensor)

In [15]:
y.dtype

torch.int32

In [16]:
y

tensor([[ 0,  0,  0],
        [ 0,  0, -1],
        [ 0,  0,  1],
        [ 0,  0,  0],
        [ 2,  0,  0]], dtype=torch.int32)