## 파이토치 참조

    https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/

In [1]:
import torch

In [2]:
torch.__version__

'1.1.0'

## 텐서 사칙 연산 

In [94]:
v = torch.tensor([1,2,3])

In [4]:
w = torch.tensor([0,10,20])

In [5]:
m = torch.tensor([[0,1,2],[100,200,300]])

##  연산 후에 새로운 사본이 생긴다

In [95]:
v2  = v + 10

In [96]:
v2

tensor([11, 12, 13])

### 연산 메소드도 새로운 사본이 생김

In [100]:
v2.add(10)

tensor([21, 22, 23])

In [101]:
v2

tensor([11, 12, 13])

###  원본을 유지하는 지를 확인 

In [8]:
import numpy as np

In [9]:
np.may_share_memory(v2, v)

False

### 단, _ 붙은  메소드는 내부 값을 갱신

In [97]:
v3 = v2.clone()

In [98]:
v3.add_(v2)

tensor([22, 24, 26])

In [99]:
v3

tensor([22, 24, 26])

###  연산 함수에는 저장장소를 지정할 수 있다.

In [106]:
r1 =torch.tensor([0,0,0])

In [107]:
torch.add(v,v2, out=r1) 

tensor([12, 14, 16])

In [108]:
r1

tensor([12, 14, 16])

In [109]:
r2 = torch.add(v,v2)

In [110]:
r2

tensor([12, 14, 16])

### 사본을 수정한 후에 원본을 확인

In [111]:
v2

tensor([11, 12, 13])

In [112]:
v2[0] = 777

In [113]:
v2

tensor([777,  12,  13])

In [114]:
v

tensor([1, 2, 3])

## 다른 연산 처리 확인 

In [13]:
v22 = v **2

In [14]:
v22

tensor([1, 4, 9])

In [15]:
v22[0] = 666

In [16]:
v22

tensor([666,   4,   9])

In [17]:
v

tensor([1, 2, 3])

In [18]:
z = v - w

In [19]:
z

tensor([  1,  -8, -17])

### 나눗셈 처리

In [20]:
w/v

tensor([0, 5, 6])

In [21]:
w//v

tensor([0, 5, 6])

## 파이토치와 넘파이 내부 속성 비교

In [22]:
tr = set(dir(torch))

In [28]:
np_ = set(dir(np))

In [34]:
len(tr & np_)

127

In [32]:
len(tr - np_)

510

In [33]:
len(np_ - tr)

497

In [35]:
m = torch.randn(100,10)

In [36]:
m.shape

torch.Size([100, 10])

In [37]:
m.dim()

2

In [38]:
m.size()

torch.Size([100, 10])

In [39]:
v = torch.randn(10)

In [40]:
v

tensor([ 0.8286, -0.3222, -0.4474,  2.3032, -1.2459,  0.4094,  0.7792, -1.8393,
        -0.3912,  0.6044])

In [41]:
v.shape

torch.Size([10])

In [42]:
v.dim()

1

In [43]:
v.size()

torch.Size([10])

## 벡터 곱

In [44]:
d = torch.dot(v,v)

In [45]:
d

tensor(12.5235)

## 행렬과 벡터 곱

In [46]:
mb = torch.dot(m,v)

RuntimeError: dot: Expected 1-D argument self, but got 2-D

In [47]:
mv = torch.mv(m,v)

In [49]:
mv.shape

torch.Size([100])

In [50]:
mv.size()

torch.Size([100])

##  행렬곱

In [54]:
m.t().shape

torch.Size([10, 100])

In [55]:
mm = torch.mm(m.t(),m)

In [56]:
mm.shape

torch.Size([10, 10])

## 모든 벡터, 행렬 곱 계산

In [58]:
mv1 = torch.matmul(m,v)

In [59]:
mv1.shape

torch.Size([100])

In [61]:
mm1 = torch.matmul(m.t(),m)

In [62]:
mm1.shape

torch.Size([10, 10])

## 고유값 분해

### 정방행렬

In [77]:
m_ = torch.randn(10,10)

In [83]:
m_

tensor([[ 0.5617, -0.6834, -0.3193,  0.2765,  0.4615, -0.4184,  0.9644, -1.2059,
          0.4145,  0.2521],
        [ 1.1277,  0.7802,  1.3930,  0.5387,  1.3719, -0.3120,  1.8863, -1.1300,
          0.4097, -0.2243],
        [-1.4714, -2.7391,  0.8302,  1.3023, -0.3672,  0.5139, -2.4585,  0.3593,
         -1.8348, -0.0607],
        [-0.2410,  0.4519, -0.1778,  0.6402, -0.3909, -2.1564,  1.9765, -0.1553,
          1.0689, -1.3187],
        [ 0.9604,  0.0501, -0.8135, -0.6197,  0.5870, -0.2134, -0.9590, -1.6533,
          0.4956,  0.3156],
        [-1.0077, -1.0140,  0.5170,  1.6771, -0.8151, -0.0849, -0.0537, -0.5967,
          0.5230, -1.2210],
        [ 0.6706,  1.3298,  0.6506,  0.1182,  0.5800, -0.2024,  1.1805,  0.2209,
          0.8445,  0.0476],
        [-0.9653,  0.4808, -0.4018, -0.4467,  0.2469,  1.8063, -1.1207, -0.0685,
         -0.2623,  0.7108],
        [-0.1686,  1.4367,  0.5543,  1.4295, -0.2121, -2.0998,  0.9111, -0.0912,
         -1.1737,  0.2996],
        [ 0.4272, -

In [78]:
e,v = torch.eig(m_, eigenvectors=True)

In [80]:
e.shape

torch.Size([10, 2])

In [84]:
e

tensor([[ 3.4709,  0.0000],
        [-0.0859,  2.9370],
        [-0.0859, -2.9370],
        [ 1.3820,  2.0334],
        [ 1.3820, -2.0334],
        [-1.3265,  0.0000],
        [-0.9739,  0.8642],
        [-0.9739, -0.8642],
        [ 0.3542,  0.8703],
        [ 0.3542, -0.8703]])

In [81]:
v.shape

torch.Size([10, 10])

In [82]:
v

tensor([[ 0.3017,  0.0718, -0.2085,  0.0339, -0.1119,  0.4460,  0.1321, -0.0797,
         -0.0300, -0.1023],
        [ 0.2232, -0.1838, -0.0887, -0.2373,  0.3046,  0.0811,  0.0515, -0.1501,
         -0.2127,  0.0288],
        [-0.6926, -0.0851, -0.3078, -0.3233, -0.3164,  0.3123, -0.3130, -0.1245,
          0.3596, -0.2791],
        [ 0.2933,  0.5687,  0.0000,  0.0151,  0.2576,  0.0155,  0.1346, -0.1027,
         -0.0363,  0.2621],
        [ 0.3189, -0.0181, -0.1387, -0.0994, -0.1269, -0.1295,  0.1392,  0.2487,
         -0.3070,  0.3900],
        [-0.2110,  0.2004, -0.4578, -0.1010,  0.2621, -0.0631,  0.1098,  0.0980,
         -0.0700, -0.0437],
        [ 0.2024, -0.0984,  0.0816,  0.0356,  0.2168, -0.4402,  0.1846,  0.1759,
          0.0872, -0.0612],
        [-0.1310, -0.2936, -0.0073,  0.1788,  0.0541,  0.3551,  0.0495,  0.0561,
          0.0969,  0.2447],
        [ 0.2029,  0.2196,  0.0788,  0.0432,  0.0902,  0.5724, -0.6764,  0.0000,
          0.2028,  0.0217],
        [ 0.2189, -

In [89]:
v

tensor([[ 0.3017,  0.0718, -0.2085,  0.0339, -0.1119,  0.4460,  0.1321, -0.0797,
         -0.0300, -0.1023],
        [ 0.2232, -0.1838, -0.0887, -0.2373,  0.3046,  0.0811,  0.0515, -0.1501,
         -0.2127,  0.0288],
        [-0.6926, -0.0851, -0.3078, -0.3233, -0.3164,  0.3123, -0.3130, -0.1245,
          0.3596, -0.2791],
        [ 0.2933,  0.5687,  0.0000,  0.0151,  0.2576,  0.0155,  0.1346, -0.1027,
         -0.0363,  0.2621],
        [ 0.3189, -0.0181, -0.1387, -0.0994, -0.1269, -0.1295,  0.1392,  0.2487,
         -0.3070,  0.3900],
        [-0.2110,  0.2004, -0.4578, -0.1010,  0.2621, -0.0631,  0.1098,  0.0980,
         -0.0700, -0.0437],
        [ 0.2024, -0.0984,  0.0816,  0.0356,  0.2168, -0.4402,  0.1846,  0.1759,
          0.0872, -0.0612],
        [-0.1310, -0.2936, -0.0073,  0.1788,  0.0541,  0.3551,  0.0495,  0.0561,
          0.0969,  0.2447],
        [ 0.2029,  0.2196,  0.0788,  0.0432,  0.0902,  0.5724, -0.6764,  0.0000,
          0.2028,  0.0217],
        [ 0.2189, -

In [90]:
torch.mv(m_,e[:,0])

tensor([ 4.0820,  6.1109, -2.9597,  0.4826,  6.4686, -1.7647,  2.3420, -4.7126,
         2.6034, -0.8911])

## 특이값 분해

In [65]:
u, s, b = torch.svd(m)

In [67]:
u.shape

torch.Size([100, 10])

In [68]:
s.shape

torch.Size([10])

In [69]:
b.shape

torch.Size([10, 10])