## 파이토치 참조

    https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/

In [1]:
import torch

In [2]:
torch.__version__

'1.1.0'

## 1차원 텐서 구하기

In [22]:
v = torch.arange(5) 

In [23]:
v

tensor([0, 1, 2, 3, 4])

In [24]:
v = torch.arange(0, 5, step=1) 

In [25]:
v

tensor([0, 1, 2, 3, 4])

In [26]:
v = torch.arange(9)

In [27]:
v

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

###  텐서 모양 바꾸기

In [28]:
v = v.view(3, 3)

In [29]:
v

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

### 1 차원 텐서 생성 마지막 값도 포함됨

In [30]:
v = torch.linspace(1, 10, steps=10) # Create a Tensor with 10 linear points for (1, 10) inclusively

In [31]:
v

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### 로그에 대한 1차원 텐서 값 처리

In [32]:
v = torch.logspace(start=-10, end=10, steps=5) # Size 5: 1.0e-10 1.0e-05 1.0e+00, 1.0e+05, 1.0e+10

In [33]:
v

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

## 단위행렬 구하기

In [3]:
eye = torch.eye(3)              # Create an identity 3x3 tensor


In [4]:
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## 특정 값을 지정해서 텐서 생성하기

In [5]:
v = torch.ones(10)              # A tensor of size 10 containing all ones

In [6]:
v

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
v = torch.ones(2, 1, 2, 1)      # Size 2x1x2x1

In [8]:
v

tensor([[[[1.],
          [1.]]],


        [[[1.],
          [1.]]]])

### 행렬의 정보를 가지고 특정 값으로 행렬을 생성하기

In [11]:
v = torch.ones_like(eye)        # A tensor with same shape as eye. Fill it with 1.

In [12]:
v

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
v = torch.zeros(10)             # A tensor of size 10 containing all zeros

In [14]:
v

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

##  특정 행렬을 만들고 값을 변경하기

In [36]:
v = torch.ones(3, 3)

In [37]:
v[1].fill_(2)

tensor([2., 2., 2.])

In [38]:
v[1].fill_(2)
v[2].fill_(3)

tensor([3., 3., 3.])

In [39]:
v

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

##   텐서 결합하기 

In [40]:
v

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

In [41]:
torch.cat((v,v, v), 0)          # Concatenate in the 0 dimension


tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

## 텐서 쌓기 

In [42]:

# Stack
r = torch.stack((v, v))

In [44]:
r

tensor([[[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.]],

        [[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.]]])

## 분리하기

In [45]:
r1 = torch.chunk(v, 3)

In [46]:
r1

(tensor([[1., 1., 1.]]), tensor([[2., 2., 2.]]), tensor([[3., 3., 3.]]))

In [47]:
r2 = torch.split(v, 2)

In [48]:
r2

(tensor([[1., 1., 1.],
         [2., 2., 2.]]), tensor([[3., 3., 3.]]))

In [53]:
v

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

## 데이터를 추출하기

In [51]:
r3 = torch.gather(v, 1, torch.LongTensor([[0,1],[1,0],[2,1]]))

In [52]:
r3

tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])

In [ ]:
cat
chunk             
gather
index_select
masked_select
nonzero
split            
squeeze
stack
t              - Transpose a 2-D tensor
take
transpose
unbind         - Removes a tensor dimension
where          - Select x or y Tensor elements based on condition Tensor c