## 파이토치 참조

    https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/

In [1]:
import torch

In [2]:
torch.__version__

'1.1.0'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.16.3'

## 텐서 만들기

       텐서는 클래스와 함수로 생성합니다.
       
       

### 텐서 클래스로  생성하기

#### 단순히 튜플로 지정하면 동일한 차원으로 텐서 생성

In [87]:
v11 = torch.Tensor(2, 3)  

In [88]:
v11

tensor([[9.8091e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

#### 배열을 지정하면 동일한 상태로 텐서를 생성

In [89]:
v22 = torch.Tensor([[1,2],[4,5]]) # A Tensor initialized with a specific array


In [90]:
v22

tensor([[1., 2.],
        [4., 5.]])

In [93]:
v22.dtype

torch.float32

#### 64비트 자료형으로 변경

In [86]:
v33 = torch.LongTensor([1,2,3])

In [91]:
v33

tensor([1, 2, 3])

In [92]:
v33.dtype

torch.int64

### 텐서를 함수로 생성

In [94]:
torch.tensor

<function _VariableFunctions.tensor>

In [5]:
t = torch.tensor([[1,2],[3,4]])

In [6]:
t

tensor([[1, 2],
        [3, 4]])

In [7]:
t.dtype

torch.int64

In [12]:
t.shape

torch.Size([2, 2])

In [13]:
t_f = torch.tensor([[3,4],[5,6]], dtype= torch.float64)

In [14]:
t_f

tensor([[3., 4.],
        [5., 6.]], dtype=torch.float64)

In [15]:
t_f.dtype

torch.float64

In [16]:
t1 = torch.arange(0,9)

In [17]:
t1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
t_0 = torch.zeros(100,10)

In [20]:
t_0.shape

torch.Size([100, 10])

In [23]:
t_0.dim()

2

#### 전체 원소의 개수

In [22]:
t_0.size()

torch.Size([100, 10])

In [73]:
torch.numel(t_0)                  # 6: number of elements in x

1000

## 텐서를 넘파이로 변환하기

In [24]:
n = t_0.numpy()

In [26]:
type(n)

numpy.ndarray

In [70]:
a = np.array([1, 2, 3])

In [71]:
v = torch.from_numpy(a) 

In [72]:
v

tensor([1, 2, 3])

### 텐서 모양 변경 

In [74]:
x = torch.randn(2, 3)            # Size 2x3

In [75]:
x.shape

torch.Size([2, 3])

#### 모양을 바꾸는 view 메소드 사용

In [76]:
y = x.view(6)     

In [78]:
y.shape

torch.Size([6])

### 전치 행렬 처리

In [99]:
x

tensor([[ 7.7770e+03, -9.2890e-01,  8.5989e-01],
        [ 5.6512e-01, -1.1921e+00, -1.5269e+00]])

In [98]:
x.t()

tensor([[ 7.7770e+03,  5.6512e-01],
        [-9.2890e-01, -1.1921e+00],
        [ 8.5989e-01, -1.5269e+00]])

In [95]:
r = torch.transpose(x, 0, 1)

In [96]:
r

tensor([[ 7.7770e+03,  5.6512e-01],
        [-9.2890e-01, -1.1921e+00],
        [ 8.5989e-01, -1.5269e+00]])

### 동일한 메모리를 공유

In [82]:
np.may_share_memory(x,y)

True

In [83]:
y[0] = 7777

In [85]:
y

tensor([ 7.7770e+03, -9.2890e-01,  8.5989e-01,  5.6512e-01, -1.1921e+00,
        -1.5269e+00])

In [84]:
x

tensor([[ 7.7770e+03, -9.2890e-01,  8.5989e-01],
        [ 5.6512e-01, -1.1921e+00, -1.5269e+00]])

### -1을 지정하면 나머지 값을 암묵적으로 정의

In [79]:
z = x.view(-1, 2)                # Size 3x2

In [81]:
z.shape

torch.Size([3, 2])

## 검색과 슬라이싱

In [28]:
t1[1]

tensor(1)

### 슬라이싱으로 부분집합을 만들어도 원본을 가지 유지함

In [30]:
t11 = t1[:5]

In [31]:
t11[0] = 999

In [33]:
t11

tensor([999,   1,   2,   3,   4])

In [34]:
t1

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8])

### 텐서를 새로운 사본으로 만들기

In [37]:
t21 = torch.clone( t1[1:6])

In [38]:
t21

tensor([1, 2, 3, 4, 5])

In [39]:
t21[0] = 999

In [40]:
t1

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8])

In [41]:
t21

tensor([999,   2,   3,   4,   5])

#### clone이나 clone.detach로 실행

In [46]:
y = t1.new_tensor(t1)

/Users/dahlmoon/anaconda/envs/pytorch/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


In [47]:
y

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8])

### 사본 만드는 다른 법

In [65]:
y1 = t1.clone().detach() #b


In [68]:
y1

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8])

In [66]:
y2 = torch.empty_like(t1).copy_(t1) 

In [69]:
y2

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8])

## 논리식 검색 

      새로운 사본을 만든다.

In [48]:
t1 > 5

tensor([1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=torch.uint8)

In [50]:
t5 = t1[t1>5]

In [51]:
t5[0] = 555

In [52]:
t5

tensor([555,   6,   7,   8])

In [53]:
t1

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8])

## 팬시 검색 

       새로운 사본을 만든다.

In [57]:
t_f = t1[[0,3,5,6]]

In [58]:
t_f

tensor([999,   3,   5,   6])

In [59]:
t1

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8])

In [60]:
t_f[0] = 777

In [61]:
t_f

tensor([777,   3,   5,   6])

In [62]:
t1

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8])