In [1]:
import torch

In [2]:
torch.__version__

'1.1.0'

##  인덱스 기준으로 조회하기

In [3]:
v = torch.arange(9)

In [4]:
v = v.view(3,3)

In [5]:
indices = torch.LongTensor([0, 2])

### 열단위로 처리 

In [6]:
r = torch.index_select(v, 1, indices)

In [7]:
r

tensor([[0, 2],
        [3, 5],
        [6, 8]])

###  행단위로 처리 

In [9]:
r1 = torch.index_select(v, 0, indices)

In [10]:
r1

tensor([[0, 1, 2],
        [6, 7, 8]])

### 논리적 마스크 선택

In [13]:
mask = v.ge(5)

In [14]:
mask

tensor([[0, 0, 0],
        [0, 0, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [15]:

r3 = torch.masked_select(v, mask)

In [16]:
r3

tensor([5, 6, 7, 8])