In [1]:
import torch
from torch.autograd import Variable


# Tensor VS Variable

## 텐서로 정의 

In [2]:
tensor = torch.rand(2,2,)

In [3]:
tensor

tensor([[0.4947, 0.5284],
        [0.0263, 0.8223]])

In [4]:
type(tensor)

torch.Tensor

In [13]:
tensor.data

tensor([[0.4947, 0.5284],
        [0.0263, 0.8223]])

In [14]:
tensor.grad

In [15]:
tensor.grad_fn

## 변수로 정의 

In [18]:
x = Variable(tensor, requires_grad=True)

In [19]:
x

tensor([[0.4947, 0.5284],
        [0.0263, 0.8223]], requires_grad=True)

In [20]:
type(x)

torch.Tensor

In [21]:
x.sum()

tensor(1.8717, grad_fn=<SumBackward0>)

In [22]:
x.grad

In [23]:
x.grad_fn

In [24]:
x

tensor([[0.4947, 0.5284],
        [0.0263, 0.8223]], requires_grad=True)

In [10]:
 x.sqrt()

tensor([[0.7034, 0.7269],
        [0.1621, 0.9068]], grad_fn=<SqrtBackward>)

In [12]:
x

tensor([[0.4947, 0.5284],
        [0.0263, 0.8223]], requires_grad=True)

In [ ]:
 x**2, x


# Variable

In [25]:
x.data

tensor([[0.4947, 0.5284],
        [0.0263, 0.8223]])

In [27]:
x.requires_grad, x.grad, x.grad_fn

(True, None, None)

In [29]:
x = Variable(torch.FloatTensor([3]), requires_grad=True)

y = x**3 + 3

z  = Variable(torch.FloatTensor([5]))

In [30]:
x.requires_grad, y.requires_grad, z.requires_grad

(True, True, False)

In [31]:
y

tensor([30.], grad_fn=<AddBackward0>)

In [32]:
y.grad_fn.next_functions[0][0]

### 미분 계산

In [33]:
y.backward()

In [35]:
x

tensor([3.], requires_grad=True)

### y의 미분 계산 값

In [36]:
 x.grad

tensor([27.])

#### grad 내의 데이터 정리

In [37]:
x.grad

tensor([27.])

In [38]:
x.grad.data.zero_()

tensor([0.])

In [39]:
 x.grad

tensor([0.])

## 두 개의 변수 정의 

In [49]:
x1 = Variable(torch.ones(2), requires_grad = True)
x2 = Variable(torch.ones(2))

In [50]:
y12 = x1 * 2 + x2

In [51]:
y12

tensor([3., 3.], grad_fn=<AddBackward0>)

In [52]:
x1.grad

In [53]:
y12.backward(torch.Tensor([1,1]))

In [54]:
x1.grad

tensor([2., 2.])

In [55]:
x2.grad

In [56]:
x1.grad.data.zero_()

tensor([0., 0.])